export const UPDATE_SESSION = "UPDATE_SESSION";
export const UPDATE_SEASON = "UPDATE_SEASON";

export const SET_AUTOMATING = "SET_AUTOMATING";
export const ACTIVATE_TIMER = "ACTIVATE_TIMER";
export const STOP_TIMER = "STOP_TIMER";

export const ADD_COMMAND = "ADD_COMMAND";
export const UPDATE_COMMAND = "UPDATE_COMMAND";
export const REMOVE_COMMAND = "REMOVE_COMMAND";
export const LOWER_ORDER_COMMAND = "LOWER_ORDER_COMMAND";
export const HIGHER_ORDER_COMMAND = "HIGHER_ORDER_COMMAND";
